"""修改tbl_admin

Revision ID: fd986e55672c
Revises: 00bc696245c9
Create Date: 2020-01-10 23:11:23.521242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd986e55672c'
down_revision = '00bc696245c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('username', sa.String(length=100), nullable=False))
    op.drop_column('admin', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('user', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.drop_column('admin', 'username')
    # ### end Alembic commands ###
